'''
El siguiente c贸digo genera un excepci贸n, utilizar un bloque try-catch para que no termine la ejecuci贸n del programa y capturar la excepci贸n que se genera. 
Imprimir el mensaje de error que se genera por pantalla.
'''

def main():
    lista = [1, 2, 3, 4, 5]
    print(lista[10])
main()
